---
$schema: "http://json-schema.org/draft-07/schema"
title: Roman Settings
type: object

allOf:
  - $ref: version-v1.0

optional:
  - backend
  - docker
  - kubernetes

additionalProperties: false
properties:
  version: {}
  environment:
    $ref: "roman_environment-v1.0#/properties/environment"
  backend:
    title: backend driver
    description: the container backend driver class
    type: string
    default: docker
  docker:
    title: docker backend options
    description: options for Docker container executor backend
    type: object
    additionalProperties: false
    properties:
      directory_map:
        title: docker conatiner-host machine path mapping
        description: The dictornary mapping between docker and it's host
        type: object
      host:
        title: docker host
        description: the URL to the Docker host
        type: string
      tls_verify:
        title: docker TLS verify
        description: verify the Docker daemon host against a CA certificate
        type: boolean
      cert_path:
        title: docker cert path
        description: a path to a directory containing TLS certificates to use when connecting to the Docker host
        type: string
      version:
        title: docker API version
        description: the version of the API to use
        type: string
      timeout:
        title: docker API timeut
        description: default timeout for API calls
        type: integer
        exclusiveMinimum: 0
  kubernetes:
    title: kubernetes backend options
    description: options for Kubernetes  backend
    type: object
    additionalProperties: false
    properties:
      namespace:
        title: default pod namespace
        description: default namesapce for generated pod which runs build container.
        type: string
